# Lab 02: Manipulate PyTorch Tensors -- exercise

In [13]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [14]:

# write your code here
A = torch.Tensor([
    [1, 2],
    [3, 4],
])
B = torch.Tensor([
    [10, 20],
    [30, 40],
])
C = A + B

print(A)
print(B)
print(C)



tensor([[1., 2.],
        [3., 4.]])
tensor([[10., 20.],
        [30., 40.]])
tensor([[11., 22.],
        [33., 44.]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [5]:

# write your code here
print(A.dim())
print(A.size())
print(A.type())


2
torch.Size([2, 2])
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [7]:

# write your code here

A = A.long()

print(A)
print(A.dim())
print(A.size())
print(A.type())


tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])
torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [11]:

# write your code here

R = torch.rand(5, 2, 3)
print(R)
print(R.type())
print(R.dim())
print(R.size())
print(R.size()[1])


tensor([[[0.8917, 0.5253, 0.8373],
         [0.7675, 0.9243, 0.7919]],

        [[0.3625, 0.5777, 0.8604],
         [0.3243, 0.7863, 0.6178]],

        [[0.2014, 0.6505, 0.6346],
         [0.0013, 0.9518, 0.1280]],

        [[0.2496, 0.8121, 0.5852],
         [0.5308, 0.3171, 0.5915]],

        [[0.6640, 0.0598, 0.4515],
         [0.3895, 0.9009, 0.9902]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [12]:

# write your code here
Z = torch.zeros(2, 3, 4, 5)
print(Z)


tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
