# Lab 01 : Linear module -- exercise

# Inspecting a linear module

In [1]:
import torch
import torch.nn as nn

### Make a linear module  WITHOUT bias that takes input of size 2 and return output of size 3. 

In [2]:
mod=nn.Linear(in_features=2, out_features=3, bias=False)    # complete here
print(mod)

Linear(in_features=2, out_features=3, bias=False)


### Print the internal parameters of the module. Try to print the bias and double check that it return you "None"

In [3]:
print(mod.weight)
print(mod.bias)

Parameter containing:
tensor([[-0.3788, -0.4634],
        [-0.5792,  0.3826],
        [ 0.6150,  0.4712]], requires_grad=True)
None


### Make a vector $x=\begin{bmatrix}1\\1 \end{bmatrix}$ and feed it to your linear module. What is the output?

In [4]:
x=  torch.ones(2) # complete here
print(x)
y=  mod(x) # complete here
print(y)

tensor([1., 1.])
tensor([-0.8422, -0.1966,  1.0861], grad_fn=<SqueezeBackward4>)


### Change the internal parameters of your module so that the weights become $
W=\begin{bmatrix}
1&2 \\ 3&4 \\ 5&6
\end{bmatrix}
$. You need to write 6 lines, one per entry to be changed.

In [5]:
with torch.no_grad():
    c = 1
    for i in range(3):
        for j in range(2):
            mod.weight[i,j] = c
            c = c + 1
    print(mod.weight)

Parameter containing:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], requires_grad=True)


### Feed the vector x to your module with updated parameters. What is the output? 

In [6]:
y= mod(x)# complete here
print(y)

tensor([ 3.,  7., 11.], grad_fn=<SqueezeBackward4>)


### Compute by hand $y=Wx$ and check that pytorch got it correctly. 

$$
\begin{bmatrix}
1&2 \\ 3&4 \\ 5&6
\end{bmatrix}
\begin{bmatrix}1\\1 \end{bmatrix}=
\begin{bmatrix}?\\? \\ ? \end{bmatrix}
$$

In [7]:
W = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
x = torch.tensor([1, 1])

y = W @ x
print(y)


tensor([ 3,  7, 11])
