# Lab 01 : Linear module -- demo

In [1]:
import torch
import torch.nn as nn

### Make a _Linear Module_ that takes input of size 5 and return output of size 3

In [2]:
mod = nn.Linear(5,3)
print(mod)

Linear(in_features=5, out_features=3, bias=True)


### Let's make a random tensor of size 5:

In [3]:
x=torch.rand(5)
print(x)
print(x.size())

tensor([0.0422, 0.4568, 0.3565, 0.5819, 0.9548])
torch.Size([5])


### Feed it to the module:

In [4]:
y=mod(x)
print(y)

tensor([ 0.0716, -0.4593, -0.1202], grad_fn=<ViewBackward0>)


### The output y is computed according to the formula:
$$
\begin{bmatrix}
y_1\\ y_2 \\y_3 
\end{bmatrix} =
\begin{bmatrix}
w_{11} & w_{12} & w_{13}& w_{14}& w_{15} \\
w_{21} & w_{22} & w_{23}& w_{24}& w_{25} \\
w_{31} & w_{32} & w_{33}& w_{34}& w_{35} \\
\end{bmatrix}
\begin{bmatrix}
x_1\\ x_2 \\x_3 \\ x_4 \\x_5
\end{bmatrix}
+
\begin{bmatrix}
b_1\\ b_2 \\b_3 
\end{bmatrix}
$$
### were the $w_{ij}$'s are the weight parameters and the $b_i$'s are the bias parameters. These internal parameters can be access as follow:

In [5]:
print(mod.weight)
print(mod.weight.size())

Parameter containing:
tensor([[ 0.1219, -0.2546, -0.3721,  0.3566,  0.3213],
        [-0.1172, -0.0523, -0.2610, -0.2122,  0.0004],
        [ 0.1846,  0.0583,  0.2510, -0.1116,  0.0508]], requires_grad=True)
torch.Size([3, 5])


In [6]:
print(mod.bias)
print(mod.bias.size())

Parameter containing:
tensor([-0.1988, -0.2144, -0.2277], requires_grad=True)
torch.Size([3])


### If we want we can change the internal parameters of the module:

In [7]:
with torch.no_grad():
    mod.weight[0,0]=0
    mod.weight[0,1]=1
    mod.weight[0,2]=2
    print(mod.weight)

Parameter containing:
tensor([[ 0.0000e+00,  1.0000e+00,  2.0000e+00,  3.5664e-01,  3.2128e-01],
        [-1.1721e-01, -5.2269e-02, -2.6102e-01, -2.1218e-01,  4.2607e-04],
        [ 1.8460e-01,  5.8303e-02,  2.5095e-01, -1.1165e-01,  5.0834e-02]],
       requires_grad=True)


### We can also make a Linear module without bias:

In [8]:
mod2 = nn.Linear(5,3,bias=False)
print(mod2)

Linear(in_features=5, out_features=3, bias=False)


In [9]:
print(mod2.weight)

Parameter containing:
tensor([[ 0.1336,  0.3503, -0.2849, -0.1423, -0.0601],
        [ 0.1321, -0.1060,  0.0678,  0.1818, -0.0358],
        [-0.4348, -0.2722, -0.1087,  0.1238, -0.3999]], requires_grad=True)


In [10]:
print(mod2.bias)

None
