# Lab 01 : Convolutional layer - demo

In [6]:
import torch
import torch.nn as nn

### Make a convolutional module
* inputs:  2 channels
* output:  5 activation maps 
* filters are 3x3
* padding with one layer of zero to not shrink anything

In [7]:
mod = nn.Conv2d(in_channels=2 , out_channels=5 ,  kernel_size=3,  padding=1 )

### Make an input 2 x 6 x 6  (two channels, each one has 6 x 6 pixels )

In [8]:
bs=1

x=torch.rand(bs,2,6,6)

print(x)

print(x.size())

tensor([[[[0.0468, 0.2227, 0.4962, 0.6561, 0.8344, 0.9062],
          [0.4777, 0.8146, 0.6837, 0.6004, 0.1891, 0.3571],
          [0.4475, 0.8335, 0.7440, 0.5550, 0.7430, 0.1000],
          [0.4970, 0.9626, 0.6106, 0.5529, 0.4108, 0.6002],
          [0.3665, 0.0303, 0.6496, 0.8628, 0.3221, 0.7619],
          [0.7857, 0.4026, 0.1675, 0.7670, 0.7725, 0.2591]],

         [[0.0234, 0.8670, 0.1923, 0.6397, 0.6363, 0.9248],
          [0.0964, 0.7568, 0.8198, 0.4674, 0.2603, 0.0871],
          [0.1862, 0.8239, 0.6447, 0.6277, 0.2911, 0.1673],
          [0.8222, 0.4302, 0.0092, 0.0181, 0.8236, 0.3421],
          [0.0741, 0.0838, 0.1456, 0.1412, 0.1089, 0.2105],
          [0.8575, 0.2293, 0.9936, 0.4548, 0.9982, 0.3148]]]])
torch.Size([1, 2, 6, 6])


### Feed it to the convolutional layer: the output should have 5 channels (each one is 6x6)

In [9]:
y=mod(x)

print(y)

print(y.size())

tensor([[[[ 0.3519,  0.2759,  0.3807,  0.3566,  0.4162,  0.2691],
          [ 0.1879,  0.5690,  0.4894,  0.3196,  0.1555,  0.2860],
          [ 0.3504,  0.4044,  0.4033,  0.3647,  0.3526,  0.2544],
          [ 0.1093,  0.2614,  0.3606,  0.3493,  0.3411,  0.1685],
          [ 0.2883,  0.3913,  0.3633,  0.2630,  0.2156,  0.4143],
          [ 0.2701,  0.3095,  0.2948,  0.4454,  0.2362,  0.2647]],

         [[-0.2335, -0.2100, -0.1312,  0.0638, -0.0337, -0.1130],
          [-0.2350, -0.2161, -0.0581, -0.0874, -0.0538, -0.0687],
          [-0.2753, -0.1314, -0.1349, -0.0989, -0.2169, -0.0122],
          [-0.1012, -0.1120, -0.2761, -0.1036, -0.0912, -0.2615],
          [-0.3033,  0.3352,  0.0398,  0.1317,  0.0152,  0.0826],
          [-0.1013, -0.0834,  0.0338, -0.1285,  0.0639, -0.1660]],

         [[ 0.1338, -0.1119, -0.1795, -0.1637, -0.2419, -0.1601],
          [-0.1033, -0.0522, -0.2669,  0.0327, -0.0315,  0.3566],
          [-0.3541, -0.0843,  0.0971,  0.0752, -0.0094,  0.0845],
      

### Lets look at the 5 filters.
* Our filters are 2x3x3
* Each of the filter has 2 channels because the inputs have two channels

In [10]:
print(mod.weight)

print(mod.weight.size())

Parameter containing:
tensor([[[[-0.0984,  0.1198, -0.0251],
          [ 0.0363,  0.1097, -0.0212],
          [-0.1896, -0.0091,  0.1049]],

         [[ 0.2064,  0.1128, -0.2300],
          [ 0.0295,  0.0731,  0.2070],
          [ 0.1215,  0.1204,  0.0363]]],


        [[[ 0.0891,  0.0278,  0.1878],
          [ 0.0937,  0.0389,  0.0769],
          [ 0.1252, -0.1853, -0.1376]],

         [[-0.1230, -0.0933, -0.1321],
          [-0.1351, -0.0297, -0.0616],
          [ 0.2302, -0.1073,  0.1766]]],


        [[[ 0.2107,  0.0294, -0.1544],
          [ 0.1511, -0.0200, -0.2198],
          [ 0.1903,  0.0020,  0.1527]],

         [[-0.1387,  0.1930, -0.0619],
          [-0.2019, -0.1737, -0.0249],
          [ 0.0373, -0.2107,  0.1471]]],


        [[[ 0.0446, -0.1479,  0.1897],
          [-0.2075,  0.0858,  0.1926],
          [ 0.0314, -0.0690,  0.0647]],

         [[ 0.0647, -0.2138,  0.1452],
          [ 0.1424, -0.1071,  0.0955],
          [ 0.2182,  0.0048, -0.1221]]],


        [[[-0.0601